### ISSUE TITLE
VM access documentation

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/hades#10]
- Explain VPN
- Remote desktop solutions (X windows client (see with Gaspoz))
- Explain IP assignation

**Comment by pmudry** [comment]
Update web site for explaining all this

**Comment by RandomReaper** [comment]
There is now tools and [documentation](http://hevs-isi.github.io/hades/doc/tools/) for accessing VMs in a simple way and without VPN, using the ssh server of hades.hevs.ch for forwarding traffic to the VMs. Access has been simplified for ssh, vnc and scp (file transfer).

I'll do the X11 forwarding documentation tomorrow.
