### ISSUE TITLE
OpenGL in VM

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/hades#13]
at least in software rendering or on x forwarding

**Comment by RandomReaper** [comment]
ANSYS Electronics Desktop fails with the following message : failed to initialize an OpenGL view.
Help says it needs opengl 2.0.

**Comment by pmudry** [comment]
See there maybe : http://serverfault.com/questions/174003/how-can-opengl-graphics-be-displayed-remotely-using-vnc

**Comment by RandomReaper** [comment]
`glxgears -info` says `GL_VRESION = 3.0 Mesa 10.5.9`. So (software-rendered) OpenGL is working.
It seems more likely than ANSYS is not properly configured, or searching for something other that the error message (and the documentation is saysing).

We could give a try with red hat or suse, which are supported by ansys.

**Comment by RandomReaper** [comment]
ANSYS complains about OpenGL, but I still think it's a problem with library dependencies.

ANSYS Electronics Desktop can is working on Centos 7. The detailed install procedure is in the [wiki](../wiki/ANSYS-Electronics).

Closing since we have a workaround.
