### ISSUE TITLE
Keyboard layout wrong in web based console

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/hades#2]

**Comment by RandomReaper** [comment]
I think there are so many layers (client OS / client browser / vnc proxy / VM OS / VM application) it will be simpler to use a standalone viewer.

It is possible to use ssh to create a tunnel for forwarding vnc. For instance : 

```
ssh pim@hades.hevs.ch -L 1234:node3:5900 -N
```

and then connect the vnc client to localhost:1234, using that the keyboard layout works
- an account on hades can be created for only ssh tunneling. (not using `pim` which is my personal account).
- 1234 is the local port, and can be choosen freely (must be >1024 and not in use).
- node3 is the host machine, this can be found in the dashboard
- 5900 is the port on the host machine. This one is more complicated to get (command line in the host machine...).

For a better user experience:
- modify `nova-api get-vnc-console` to support our console-type.
- add a link in the dashboard for connecting to this ssh+vnc console
- a custom url handler is relatively easy to implement, something like `ssh+vnc://`.

**Comment by decaixj** [comment]
I tried the command ssh dej@hades.hevs.ch -L 1234:test:5900 -N
But it does not recognize my password whereas I succeeded to log using the web window.

**Comment by RandomReaper** [comment]
Dear @decaixj,

The keyboard layout over the web based console will probably never work.
We are currently working on alternative solutions:
- [Without GUI](../wiki/Access-to-virtual-machines).
- Using a VNC server on the client (work in progress).
- Using a remote X display (work in progress).

Best regards

Marc

**Comment by RandomReaper** [comment]
@decaixj
There is now some new documentation for remote access [here](http://hevs-isi.github.io/hades/doc/tools/).

**Comment by pmudry** [comment]
@decaixj  @RandomReaper  

Web-based console is not usable without a proper US keyboard. This won't be fixed as alternatives exist (VNC, SSH etc...). See the documentation from the last comment.
