### ISSUE TITLE
VPN access

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/hades#5]
- Document it using HEVS tools 
- Install other ?

**Comment by RandomReaper** [comment]
Dear @pmudry,

Could you please test the two following links, from the outside:
- https://sinf.hevs.ch/fr-fr/Ressources/R%C3%A9seau/VPN
- http://remote.hevs.ch/

If the VPN fonctionnality is working, can you test if hades.hevs.ch is resolvable using DNS?

Thank you in advance

Marc

**Comment by pmudry** [comment]
Dear @RandomReaper,

Will do ! However, is there a pulse client for Linux ?

**Comment by RandomReaper** [comment]
It seems that `openconnect` can do that, I'll try it.

**Comment by RandomReaper** [comment]
Working with ubuntu 15.04.

```
sudo apt-get install openconnect
sudo openconnect --juniper remote.hevs.ch
```

Routes are wrong, can be fixed using `sudo route add -net 153.109.0.0 netmask 255.255.0.0 dev tun0`

**Comment by pmudry** [comment]
@RandomReaper, please document VPN access ASAP on the website.

**Comment by RandomReaper** [comment]
@pmudry,

So which way did you use from windows?

**Comment by pmudry** [comment]
Pulse is working flawlessly with kitty and the config we checked the other day.

**Comment by RandomReaper** [comment]
new [Document](http://hevs-isi.github.io/hades/doc/vpn/)

**Comment by pmudry** [comment]
Many users report that it is working now. Closing
